blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/FortySevenEffects/arduino_midi_library/discussions
    about: Not a bug or a feature request ? Discuss your problem, ask for help or show what you've built in Discussions.
