#ifndef MIDIFUNCTIONS_STUBS_H_OINO0AUK
#define MIDIFUNCTIONS_STUBS_H_OINO0AUKMIDIFUNCTIONS_STUBS_H_OINO0AUK

#define SIM_UIDMH 1
#define SIM_UIDL 1
#define SIM_UIDML 1
#define SIM_UIDH 1


#endif /* end of include guard: MIDIFUNCTIONS_STUBS_H_OINO0AUKMIDIFUNCTIONS_STUBS_H_OINO0AUK */
