SET(TARGET_TRIPLET "arm-none-eabi")

SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER ${TARGET_TRIPLET}-gcc)
SET(CMAKE_CXX_COMPILER ${TARGET_TRIPLET}-g++)
SET(CMAKE_ASM_COMPILER ${TARGET_TRIPLET}-gcc)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)

SET(CMAKE_OBJCOPY ${TARGET_TRIPLET}-objcopy CACHE INTERNAL "objcopy tool")
SET(CMAKE_OBJDUMP ${TARGET_TRIPLET}-objdump CACHE INTERNAL "objdump tool")

SET(CMAKE_FIND_ROOT_PATH  ${EXTRA_FIND_PATH})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

MESSAGE(STATUS "BUILD_TYPE: " ${CMAKE_BUILD_TYPE})
